/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Password;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Sarmientos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Password pas;
    int longitud;
    String contraseña;

    public Principal() {
        initComponents();
        cmdCrearContraseña.setEnabled(true);
        cmdCambiarContraseña.setEnabled(false);
        cmdSeguridad.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
        txtPasNuevaContraseña.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPasContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtPasNuevaContraseña = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        cmdCrearContraseña = new javax.swing.JButton();
        cmdCambiarContraseña = new javax.swing.JButton();
        cmdSeguridad = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 30));

        txtPasContraseña.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        getContentPane().add(txtPasContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 240, 30));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel2.setText("Nueva Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        txtPasNuevaContraseña.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        getContentPane().add(txtPasNuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 240, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrearContraseña.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdCrearContraseña.setText("Crear Contraseña");
        cmdCrearContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCrearContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, -1));

        cmdCambiarContraseña.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdCambiarContraseña.setText("Cambiar contraseña");
        cmdCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, -1));

        cmdSeguridad.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdSeguridad.setText("Tipo de seguridad");
        cmdSeguridad.setToolTipText("Saber si la contraseña es fuerte o no\n");
        cmdSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeguridadActionPerformed(evt);
            }
        });
        jPanel1.add(cmdSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, -1));

        cmdMostrar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, -1));

        cmdLimpiar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 220, 260));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 400, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 51, 51))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 400, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearContraseñaActionPerformed
        if (txtPasContraseña.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Contraseña", "error", JOptionPane.ERROR_MESSAGE);
            txtPasContraseña.requestFocusInWindow();
        } else {
            contraseña = txtPasContraseña.getText();
            longitud = contraseña.length();
            pas = new Password(longitud, contraseña);
            JOptionPane.showMessageDialog(this, "Contraseña guardada");
            cmdCambiarContraseña.setEnabled(true);
            cmdSeguridad.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdLimpiar.setEnabled(true);
            cmdCrearContraseña.setEnabled(false);
            txtPasContraseña.setEditable(false);
            txtPasNuevaContraseña.setEditable(true);
        }
    }//GEN-LAST:event_cmdCrearContraseñaActionPerformed

    private void cmdCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarContraseñaActionPerformed
        txtResultado.setText("");
        String nueva;
        int longitud;
        int password = 1;
        if (txtPasNuevaContraseña.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Nueva Contraseña", "error", JOptionPane.ERROR_MESSAGE);
            txtPasNuevaContraseña.requestFocusInWindow();
        } else {
            nueva = txtPasNuevaContraseña.getText();
            longitud = nueva.length();
            pas = new Password(longitud, contraseña);
            pas.CambiarContraseña(nueva, longitud);
            JOptionPane.showMessageDialog(this, "Contraseña actualizada");
        }

    }//GEN-LAST:event_cmdCambiarContraseñaActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        String aux;
        aux = pas.mostrar();
        txtResultado.setText(aux);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeguridadActionPerformed
        String c;
        c = pas.fuerte();
        txtResultado.setText(c);
    }//GEN-LAST:event_cmdSeguridadActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtPasContraseña.setText("");
        txtPasNuevaContraseña.setText("");
        txtResultado.setText("");
        cmdCrearContraseña.setEnabled(true);
        cmdCambiarContraseña.setEnabled(false);
        cmdSeguridad.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
        txtPasContraseña.setEditable(true);
        txtPasContraseña.requestFocusInWindow();
        txtPasNuevaContraseña.setEditable(false);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCambiarContraseña;
    private javax.swing.JButton cmdCrearContraseña;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdSeguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtPasContraseña;
    private javax.swing.JPasswordField txtPasNuevaContraseña;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
