/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Complejos;
import clases.ComplejosDivisionCeroException;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Sarmientos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtImaginario1 = new javax.swing.JTextField();
        txtReal1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbOperacion = new javax.swing.JComboBox<>();
        txtImaginario2 = new javax.swing.JTextField();
        txtReal2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtImaginario3 = new javax.swing.JTextField();
        txtReal3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Números complejos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        txtImaginario1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        getContentPane().add(txtImaginario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 70, -1));

        txtReal1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        getContentPane().add(txtReal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, -1));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("(                    +                     i  )");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 20));

        cmbOperacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbOperacion.setForeground(new java.awt.Color(255, 51, 51));
        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "−", "×", "÷" }));
        getContentPane().add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        txtImaginario2.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        getContentPane().add(txtImaginario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 70, -1));

        txtReal2.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        getContentPane().add(txtReal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 70, -1));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("(                    +                     i  )");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 200, 20));

        txtImaginario3.setEditable(false);
        txtImaginario3.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        txtImaginario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImaginario3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtImaginario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 70, -1));

        txtReal3.setEditable(false);
        txtReal3.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        getContentPane().add(txtReal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 70, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("(                             +                              i  )");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 210, 20));

        cmdCalcular.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        cmdLimpiar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("  =");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 20, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtImaginario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImaginario3ActionPerformed
        
    }//GEN-LAST:event_txtImaginario3ActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        int op;
        double real1, real2, imaginario1, imaginario2;
        Complejos comple1, comple2, comple3 = null;
        int sw = 1;

        if (txtReal1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "digite número real del complejo  1", "Error", JOptionPane.ERROR_MESSAGE);
            txtReal1.requestFocusInWindow();
        } else if (txtImaginario1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "digite número imaginario del complejo 1", "Error", JOptionPane.ERROR_MESSAGE);
            txtImaginario1.requestFocusInWindow();
        } else if (txtReal2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "digite número real del complejo 2", "Error", JOptionPane.ERROR_MESSAGE);
            txtReal2.requestFocusInWindow();
        } else if (txtImaginario2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "digite número imaginario del complejo 2", "Error", JOptionPane.ERROR_MESSAGE);
            txtImaginario2.requestFocusInWindow();
        } else {
            try {
                real1 = Integer.parseInt(txtReal1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El número real del complejo 1 debe ser valido", "Error", JOptionPane.ERROR_MESSAGE);
                txtReal1.requestFocusInWindow();
                txtReal1.selectAll();
                sw = 0;
            }
            try {
                imaginario1 = Integer.parseInt(txtImaginario1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El número imaginario del complejo 1 debe ser valido", "Error", JOptionPane.ERROR_MESSAGE);
                txtImaginario1.requestFocusInWindow();
                txtImaginario1.selectAll();
                sw = 0;
            }
            try {
                real2 = Integer.parseInt(txtReal2.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El número real del complejo 2 debe ser valido", "Error", JOptionPane.ERROR_MESSAGE);
                txtReal2.requestFocusInWindow();
                txtReal2.selectAll();
                sw = 0;
            }
            try {
                imaginario2 = Integer.parseInt(txtImaginario2.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El número imaginario del complejo 2 debe ser valido", "Error", JOptionPane.ERROR_MESSAGE);
                txtImaginario2.requestFocusInWindow();
                txtImaginario2.selectAll();
                sw = 0;
            }
            if (sw == 1) {
                op = cmbOperacion.getSelectedIndex();
                real1 = Integer.parseInt(txtReal1.getText());
                imaginario1 = Integer.parseInt(txtImaginario1.getText());
                real2 = Integer.parseInt(txtReal2.getText());
                imaginario2 = Integer.parseInt(txtImaginario2.getText());

                try {
                    comple1 = new Complejos(real1, imaginario1);
                    comple2 = new Complejos(real2, imaginario2);

                    switch (op) {
                        case 0:
                        comple3 = comple1.sumar(comple2);
                        break;
                        case 1:
                        comple3 = comple1.restar(comple2);
                        break;
                        case 2:
                        comple3 = comple1.multiplicar(comple2);
                        break;
                        case 3:
                        comple3 = comple1.dividir(comple2);
                        break;
                    }
                    txtReal3.setText(" " + comple3.getReal());
                    txtImaginario3.setText(" " + comple3.getImag());
                } catch (ComplejosDivisionCeroException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    if (real2 == 0) {
                        txtReal2.requestFocusInWindow();
                        txtReal2.selectAll();
                    } else if (imaginario2 == 0) {
                        txtImaginario2.requestFocusInWindow();
                        txtImaginario2.selectAll();
                    }
                }
            }
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtReal1.setText("");
        txtImaginario1.setText("");
        txtReal2.setText("");
        txtImaginario2.setText("");
        txtReal3.setText("");
        txtImaginario3.setText("");
        cmbOperacion.setSelectedIndex(0);
        txtReal1.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtImaginario1;
    private javax.swing.JTextField txtImaginario2;
    private javax.swing.JTextField txtImaginario3;
    private javax.swing.JTextField txtReal1;
    private javax.swing.JTextField txtReal2;
    private javax.swing.JTextField txtReal3;
    // End of variables declaration//GEN-END:variables
}
